<?php

namespace GuestbookBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
	public function getAllPosts($page = 1, $sort = "date", $order = "DESC")
    {
        $query = $this->createQueryBuilder('p')
        ->orderBy('p.'.$sort, $order)
        ->getQuery();

    	$paginator = $this->paginate($query, $page);

   		return $paginator;
    }

    public function paginate($dql, $page = 1, $limit = 15)
	{
	    $paginator = new Paginator($dql);

	    $paginator->getQuery()
	        ->setFirstResult($limit * ($page - 1)) // Offset
	        ->setMaxResults($limit); // Limit

	    return $paginator;
	}
}
